version: "3"

services:
  database:
    container_name: eurovote_database
    restart: unless-stopped
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db_volume:/var/lib/postgresql/data/

volumes:
  db_volume:
